version: '3'

services:
  app:
    build: ./dockerfiles/nodejs/

    ports:
      # For next.js app
      - '3000:3000'
      # For Prisma studio
      - '5555:5555'

    volumes:
      - ./src/:/home/usr/app/

    environment:
      # For JavaScript, CHOKIDAR_USEPOLLING=true can be used
      # When using TypeScript,
      - WATCHPACK_POLLING=true

    command: sh -c "npm run dev"

    # Avoids normal termination of container
    tty: true

    depends_on:
      - db

    networks:
      - webapp

  db:
    build: ./dockerfiles/postgresql/
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - ./src/.env
    networks:
      - webapp

networks:
  webapp:
    # Use of default driver (bridge)
    driver: bridge
