version: '3'

services:
  app:
    build: ./containers/nodejs/

    ports:
      # For next.js app
      - "3000:3000"
      # For Prisma studio
      - "5555:5555"

    volumes:
      - ./containers/nodejs/src/:/home/usr/app/

    environment:
      # For JavaScript, CHOKIDAR_USEPOLLING=true can be used
      # When using TypeScript,
      - WATCHPACK_POLLING=true

    command: sh -c "npm run dev"

    # Avoids normal termination of container
    tty: true

    depends_on:
      - db
      # - api

    networks:
      - webapp

  db:
    build: ./containers/postgresql/
    expose:
      - "5432"
    volumes:
      - ./containers/postgresql/db/:/var/lib/postgresql/data/
    env_file:
      - ./containers/nodejs/src/.env
    networks:
      - webapp

  api:
    build: ./containers/fastapi/
    ports:
      - "8080:8080"
    volumes:
      - ./containers/fastapi/cv/:/home/usr/app/
    tty: true
    networks:
      - webapp
    command: sh -c "poetry run python server.py"

networks:
  webapp:
    # Use of default driver (bridge)
    driver: bridge
