version: "3"

services:
  app:
    build: ./app/front/

    ports:
      # For next.js app
      - "3000:3000"
      # For Prisma studio
      - "5555:5555"

    volumes:
      - ./app/front/src/:/home/usr/app/

    environment:
      # For JavaScript, CHOKIDAR_USEPOLLING=true can be used
      # When using TypeScript,
      - WATCHPACK_POLLING=true

    # Avoids normal termination of container
    tty: true

    networks:
      - appnetwork

    # If running "npm install" inside Dockerfile, due to bind mount,
    # local node_modules (empty) is overriden after image build
    # As volumes are applied after bind mount, using named or anonymous volume,
    # node_modules created during image build will be set
    command: >
      sh -c "
        npm install &&
        npx prisma generate &&
        npm run dev
      "

  api:
    build: ./app/api/
    ports:
      - "8080:8080"
    volumes:
      - ./app/api/src/:/home/usr/app/
    tty: true
    networks:
      - appnetwork
    command: sh -c "poetry run python server.py"

networks:
  appnetwork:
    # Use of default driver (bridge)
    driver: bridge
